### PR TITLE
updated confirmation messages for countup/down

### PR DESCRIPTION
**Pull request by fluffychaos**
Update the outputs of commands to contain the discord ID and battle tag of the players

### CODE REVIEW

**Comment by fluffychaos** [comment]
Currently only the /countup and /countdown commands got touched. If we want more commands to be edited in this way let me know.

**Comment by fluffychaos** [comment]
Also if you care about a no-so-messy commit history I recommend cherry picking the seocnd commit in this PR. The other 2 commits were the result of me messing up in my PR before.

**Comment by fdendorfer** [comment]
@fluffychaos can you add the following line between the "BattleTag" and the "Old Value" fields and after "New Value"? It contains some 0 width spaces, so the value fields appear on a new line

```javascript
{ name: '​', value: '​', inline: true },
```

**Review by fluffychaos — COMMENTED** [review]
embeds now contain the empty fields

**Pull request merged**
