### PR TITLE
Role and Channel validation helpers

### PR DESCRIPTION
**Pull request by fdendorfer**
Just an idea I had. What do you think about it @Dogers

### CODE REVIEW

**Comment by Dogers** [comment]
Seems alright! Can we use it elsewhere too?

**Review by Dogers — APPROVED** [review]
image

**Comment by Dogers** [comment]
Looks okay to me, no reported issues (with this!) after giving it a scan with the tools :)

**Review by fdendorfer — COMMENTED** [review]
Tested ok

**Pull request merged**
