### PR TITLE
craeted simple user documentation

### PR DESCRIPTION
**Pull request by fluffychaos**
With this commit we have a simple user documentation for the SVBot. The developer documentation still needs to be created

### CODE REVIEW

**Review by fluffychaos — COMMENTED** [review]
With these changes we will have an user dcumentation to start with. Developer documentation still needs to be created

**Comment by fdendorfer** [comment]
Revert the yarn.lock and remove the package-lock.json, then it looks good. There's also some typos that can be fixed later

**Comment by Dogers** [comment]
@fdendorfer should one or both of them not be in gitignore? I've removed the package-lock from this PR tho

**Comment by fdendorfer** [comment]
I commented on this already in the other MR #12 which I guess I can close.

> Don't want this. The developer docs should cover that the package manager for this project is yarn 1.22 and that lockfiles shouldn't change unless package.json has changed. The yarn.lock file stays in, so the deployment script can use yarn install --frozen-lockfile, which makes sure it installs the exact same versions as the developer that merged it

**Comment by Dogers** [comment]
Bam, sorted :)

**Pull request merged**
